{"name": "Если создать пользователя с логином, который уже есть, возвращается ошибка", "status": "passed", "steps": [{"name": "Создание курьера", "status": "passed", "parameters": [{"name": "login", "value": "'teyaisqrqf'"}, {"name": "password", "value": "'cczmmnbkaa'"}, {"name": "first_name", "value": "'anivpxyywp'"}], "start": 1739802075180, "stop": 1739802075419}], "start": 1739802075180, "stop": 1739802075421, "uuid": "49647b2a-86b1-46bd-8fdb-aa877ead5c28", "historyId": "03e94fc45bd33900dabc3be245e2aa2e", "testCaseId": "03e94fc45bd33900dabc3be245e2aa2e", "fullName": "tests.tests_methods_courier.TestCouriers#test_create_duplicate_courier", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "tests_methods_courier"}, {"name": "subSuite", "value": "TestCouriers"}, {"name": "host", "value": "DESKTOP-5IUKQF9"}, {"name": "thread", "value": "13228-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.tests_methods_courier"}]}