{"name": "Система возвращает ошибку, если неправильно указать пароль", "status": "passed", "steps": [{"name": "Логинимся", "status": "passed", "parameters": [{"name": "login", "value": "'invalid_login'"}, {"name": "password", "value": "'valid_password'"}], "start": 1739525484258, "stop": 1739525484436}], "start": 1739525484257, "stop": 1739525484438, "uuid": "76ae38a3-85ab-4bd4-8113-db05a0b94a5b", "historyId": "e6812574981c1d02529bfd69aacf61a3", "testCaseId": "e6812574981c1d02529bfd69aacf61a3", "fullName": "tests.tests_login.TestLogin#test_password_courier_invalid_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "tests_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-5IUKQF9"}, {"name": "thread", "value": "11416-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.tests_login"}]}