{"name": "Если создать пользователя с логином, который уже есть, возвращается ошибка", "status": "passed", "steps": [{"name": "Сначала создаем курьера, чтобы потом его удалит", "status": "passed", "start": 1739525497171, "stop": 1739525497405}, {"name": "Создание курьера", "status": "passed", "parameters": [{"name": "login", "value": "'mnyosbjwwl'"}, {"name": "password", "value": "'ogeadpogjn'"}, {"name": "first_name", "value": "'inqutvspiy'"}], "start": 1739525497406, "stop": 1739525497587}], "start": 1739525497171, "stop": 1739525497588, "uuid": "ea91494f-914e-4b77-9eae-d03e40d6fa66", "historyId": "03e94fc45bd33900dabc3be245e2aa2e", "testCaseId": "03e94fc45bd33900dabc3be245e2aa2e", "fullName": "tests.tests_methods_courier.TestCouriers#test_create_duplicate_courier", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "tests_methods_courier"}, {"name": "subSuite", "value": "TestCouriers"}, {"name": "host", "value": "DESKTOP-5IUKQF9"}, {"name": "thread", "value": "9280-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.tests_methods_courier"}]}